// E:\woneview\app\layout.tsx

import type { Metadata } from "next";
import { Geist, Nunito, Nunito_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";
import FloatingForm from "./component/FloatingForm";
// import FooterSection from "./component/FooterSection";
import SmoothScroll from "./component/SmoothScroll";
import Footer2 from "./component/Footer2";
import Navbar2 from "./component/Navbar2";
// import { Lexend } from "next/font/google";




// const MainFont = Lexend({
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
//   subsets: ["latin"],
// });

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">

      <body className={`${nunitoSans.className} antialiased`}>

        {/* <Navbar /> */}
        <Navbar2 />
        <FloatingForm />

        <SmoothScroll>
          <main>{children}</main>
          {/* <FooterSection /> */}
          <Footer2 />
        </SmoothScroll>
      </body>
    </html>
  );
}
