// // E:\woneview\app\layout.tsx

// import type { Metadata } from "next";
// import {
//   Geist,
//   Nunito,
//   Nunito_Sans,
//   Montserrat,
//   Bricolage_Grotesque,
// } from "next/font/google";
// import "./globals.css";
// import Navbar from "./component/Navbar";
// import FloatingForm from "./component/FloatingForm";
// // import FooterSection from "./component/FooterSection";
// import SmoothScroll from "./component/SmoothScroll";
// import Footer2 from "./component/Footer2";
// import Navbar2 from "./component/Navbar2";

// // const nunitoSans = Nunito_Sans({
// //   subsets: ["latin"],
// //   weight: ["200", "300", "400", "500", "600", "700", "800"],
// //   display: "swap",
// // });

// const montserrat = Montserrat({
//   subsets: ["latin"],
//   variable: "--font-montserrat",
//   display: "swap",
// });
// const bricolage = Bricolage_Grotesque({
//   subsets: ["latin"],
//   variable: "--font-bricolage",
//   display: "swap",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       {/* <body className={`${nunitoSans.className} antialiased`}> */}
//       <body
//         className={`${bricolage.variable} ${montserrat.variable}  antialiased`}
//       >
//         {/* <Navbar /> */}
//         <Navbar2 />
//         <FloatingForm />

//         <SmoothScroll>
//           <main>{children}</main>
//           {/* <FooterSection /> */}
//           <Footer2 />
//         </SmoothScroll>
//       </body>
//     </html>
//   );
// }

/// new
import type { Metadata } from "next";
import { Montserrat, Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import Navbar2 from "./component/Navbar2";
import FloatingForm from "./component/FloatingForm";
import SmoothScroll from "./component/SmoothScroll";
import Footer2 from "./component/Footer2";

// 1. Configure Montserrat (Secondary)
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
});

// 2. Configure Bricolage (Primary/Default)
const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-bricolage",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* NOTE: Yahan humne dono variables pass kiye hain.
         'font-sans' class lagana bahut zaruri hai.
      */}
      <body
        className={`${montserrat.variable} ${bricolage.variable} font-sans antialiased`}
      >
        <Navbar2 />
        <FloatingForm />

        <SmoothScroll>
          <main>{children}</main>
          <Footer2 />
        </SmoothScroll>
      </body>
    </html>
  );
}
